### PR TITLE
[FEATURE] Support eac client file support update

### PR DESCRIPTION
**Pull request by adibas03**

### CODE REVIEW

**Comment by Bagaric** [comment]
@adibas03 does this PR depend or any PRs to eac.js-client?

**Comment by adibas03** [comment]
Yes it does:
https://github.com/ethereum-alarm-clock/eac.js-cli/pull/3  
https://github.com/ethereum-alarm-clock/eac.js-client/pull/18

**Comment by Bagaric** [comment]
Ok. Let's merge this only after those two are merged.

**Comment by adibas03** [comment]
awaiting npm publishing of the updates

**Comment by adibas03** [comment]
all set, merging

**Pull request merged**
