### PR TITLE
Electron Icon

### PR DESCRIPTION
**Pull request by Bagaric**
Works on:
- [x] MacOS
- [ ] Linux (not working)
- [ ] Windows (Known Bug: electron/rcedit#56)

### CODE REVIEW

**Comment by adibas03** [comment]
@Bagaric 
Unable to test in Windows, met by error:
https://github.com/electron/rcedit/issues/56

**Comment by adibas03** [comment]
we should consider checking out : https://github.com/electron-userland/electron-forge

**Comment by kosecki123** [comment]
@lsaether @adibas03 could you please test with linux distro?

**Comment by Bagaric** [comment]
@adibas03 Seems that rcedit 1.1.0 should fix this. Could you check you have rcedit 1.1.0?

**Pull request merged**
