### PR TITLE
Add ability to reset timenode prove process

### PR DESCRIPTION
**Pull request by kennym**
Implements #204 

Currently the changes are not persistent, but the user is able to go back and submit a new wallet file at least.

### CODE REVIEW

**Comment by kennym** [comment]
Screenshot: 
image

**Comment by adibas03** [comment]
could you add a `Reset Wallet` button in the `TimenodeStatistics` component as well

**Comment by kennym** [comment]
@adibas03 currently can't - I'm not getting past that screen for some reason. Once I do, I will.

**Comment by Bagaric** [comment]
Great job @kennym! No need to implement the button on the main screen yet, as we're still waiting for the design decision on where to place it. This will do 👍

**Comment by kennym** [comment]
Thank you! Yes, adding that functionality to the timenode stats might be out of the scope of this one. :-)

**Pull request merged**
